POSOman/Controllers/OnlineCustomersController.cs
using Microsoft.AspNet.Identity;
using POSOman.Models;
using POSOman.Models.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POSOman.Controllers
{
    public class OnlineCustomersController : Controller
    {
        private dbPOS db = new dbPOS();
        UserActionsPerformed UserActions = new UserActionsPerformed();
        // GET: OnlineCustomers
        public ActionResult Index()
        {
            return View();
        }

        // Get Online Customer Sales Date Wise 
        public ActionResult CustomerSales(bool? isSearch, int? AccountID, DateTime? fromDate, DateTime? toDate, int? BranchId)
        {
            int branchId = 0;

            if (Session["BranchID"] != null)
            {
                branchId = Convert.ToInt32(Session["BranchID"]);
            }
            else
            {
                var user = User.Identity;
                string currentUserId = User.Identity.GetUserId();
                var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                branchId = currentUser.BranchID;
            }
            ViewBag.customer = db.tbl_OnlineCustomer.Select(v => new { Value = v.AccountID, Name = v.Name }).ToList();
            ViewBag.customerPhone = db.tbl_OnlineCustomer.Select(c => new { Value = c.AccountID, Name = c.Phone }).ToList();
            ViewBag.Branch = db.tbl_Branch.Select(b => new { Value = b.BranchID, Name = b.BranchName }).ToList();           
            if (isSearch == true)
            {
                List<GetOnlineCustomerSalesDateWise_Result> customer = db.GetOnlineCustomerSalesDateWise(AccountID, fromDate, toDate, BranchId).ToList();
                if (customer.Count == 0)
                {
                    return PartialView("_CustomerSales");
                }
                else
                    return PartialView("_CustomerSales", customer);
            }
            return View();
        }
        // Get Statement of Customer 
        public ActionResult CustomerStatement(int? AccountID, DateTime? fromDate, DateTime? toDate, int? BranchID)
        {
            ViewBag.Branch = db.tbl_Branch.Select(b => new { Value = b.BranchID, Name = b.BranchName }).ToList();
            ViewBag.customer = db.tbl_OnlineCustomer.Select(v => new { Value = v.AccountID, Name = v.Name }).ToList();            
            ViewBag.customerPhone = db.tbl_OnlineCustomer.Select(c => new { Value = c.AccountID, Name = c.Phone }).ToList();
            if (AccountID > 0)
            {
                List<GetOnlineCustomerPaymentDateWise_Result> customer = db.GetOnlineCustomerPaymentDateWise(AccountID, fromDate, toDate, BranchID).ToList();
                if (customer.Count == 0)
                {
                    return PartialView("_CustomerStatement");
                }
                else
                    return PartialView("_CustomerStatement", customer);
            }
            return View();
        }
        // Get Receiving Page
        public ActionResult Receiving()
        {
            try
            {
                int branchId = 0;

                if (Session["BranchID"] != null)
                {
                    branchId = Convert.ToInt32(Session["BranchID"]);
                }
                else
                {
                    var user = User.Identity;
                    string currentUserId = User.Identity.GetUserId();
                    var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                    branchId = currentUser.BranchID;
                }
                ViewBag.customer = db.tbl_OnlineCustomer.Select(c => new { Value = c.AccountID, Name = c.Name }).ToList();
                ViewBag.customerPhone = db.tbl_OnlineCustomer.Select(c => new { Value = c.AccountID, Name = c.Phone }).ToList();
                ViewBag.payType = db.tbl_PaymentTypes.Where(p => p.ID < 4).Select(p => new { Value = p.ID, Name = p.Name }).ToList();
                ViewBag.BankAccount = db.tbl_AccountDetails.Where(acd => acd.AccountTypeID == 27).Select(p => new { Value = p.AccountID, Name = p.AccountName + " | " + p.Bank }).ToList();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }
    }
}

POSOman/Views/OnlineCustomers/CustomerSales.cshtml
@model IEnumerable<POSOman.Models.GetOnlineCustomerSalesDateWise_Result>

@{
    ViewBag.Title = "Index";
}
<style>
    @@media print {
        html, body {
            height: 90vh;
        }
    }
</style>

<div class="content-body" id="content">
    <!-- DOM - jQuery events table -->
    <section id="dom">
        <div class="row">
            <div class="col-12">
                <h2>Online Sales</h2> <br />
                <div class="form-row">
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>From Date</label>
                        <input id="fromDate" type="date" class="form-control pickadate" placeholder="From Date" />

                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>To Date</label>
                        <input id="toDate" type="date" class="form-control pickadate" placeholder="To Date" />
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>Customer</label>
                        <input type="hidden" id="hdnAccountID" name="hdnAccountID">
                        <div class="input-group">
                            @Html.DropDownList("AccountID", new SelectList(ViewBag.customer, "Value", "Name"), "Select Customer", htmlAttributes: new { @class = "select2 form-control" })
                        </div>
                    </div>                    
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>Phone</label>
                        <br>
                        @Html.DropDownList("CustomerPhone", new SelectList(ViewBag.customerPhone, "Value", "Name"), "Select Phone", htmlAttributes: new { @class = "select2 form-control" })
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-1" hidden>
                        <label>Branch</label>
                        <div class="input-group">
                            @Html.DropDownList("Branch", new SelectList(ViewBag.Branch, "Value", "Name"), "Branch", htmlAttributes: new { @class = "select2 form-control" })
                        </div>
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label></label>
                        <br>
                        <button type="button" class="btn btn-primary" id="btnSearch">Search</button>
                    </div>
                </div>


                <div id="SearchResult">

                </div>
            </div>
        </div>

    </section>
</div>
@section scripts{

    <link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/sweetalert.css">
    <script src="~/Scripts/vendor/js/extensions/sweetalert.min.js" type="text/javascript"></script>


    <script>
        $("#AccountID").change(function () {
            var customerID = $('#AccountID').val();
            $('#hdnAccountID').val(customerID);
            $('#CustomerPhone').val(customerID).trigger('change.select2');
        });
       
        $("#CustomerPhone").change(function () {
            var customerID = $('#CustomerPhone').val();
            $('#hdnAccountID').val(customerID);
            $('#AccountID').val(customerID).trigger('change.select2');
        });
        $("#AccountID").select2();
        $("#CustomerPhone").select2();
        $("#btnSearch").on("click", function () {
            var BranchID = $('#Branch').val();
            var accountID = $('#hdnAccountID').val();
            var fromDate = $('#fromDate').val();
            var toDate = $('#toDate').val();
            var html = "<h3 style=align=center>Online Customer Sales Report</h3><br/>";
            var Branch = $("#Branch option:selected").text();
            if (BranchID != "")
            { html += "<h3>Branch:  " + Branch + "</h3></br>"; }
            var vendorName = $("#AccountID option:selected").text();
            var customerCode = $("#CustomerCode option:selected").text();
            if (accountID > 0)
            { html += "<h3>Customer :  " + customerCode + " | " + vendorName + "</h3></br>"; }
            if (fromDate != "" && toDate != "")
            { html += "<h3>From:    " + fromDate + "            TO:    " + toDate + " </h3></br>"; }
            {
                $.ajax({
                    url: "@Url.Action("CustomerSales", "OnlineCustomers")",
                    data: {
                        isSearch:true,
                        accountID: accountID,
                    fromDate  : $('#fromDate').val(),
                    toDate: $('#toDate').val(),
                    BranchID : BranchID
                    },
                    success: function (data) {
                        if (data != null) {
                            $("#SearchResult").html(data);
                            //$.fn.dataTable.moment('D/M/YYYY', 'en-US');
                            $('#tblSO').dataTable({
                                aoColumnDefs: [
                                 
                                { "aTargets": [0], "bSortable": true },
                                { "aTargets": [3], "bSortable": true },                                
                                { "aTargets": [1], "bSortable": true },
                                { "aTargets": [2], "bSortable": true, "sType": "datetime-moment" },
                                ],
                                dom: 'Bfrtip',
                                buttons: [
                                    {
                                        extend: 'print',
                                        title: '',
                                        messageTop: function () {
                                            return '<img src="@ViewBag.Picture" class="brand-logo" align = "left" margin="10px"><h1 align="center">@ViewBag.CompanyName</h1><h5 align="center">@ViewBag.CompanyAddress</h5><h5 align="center">@ViewBag.CompanyLandline</h5><hr /><h4 align="center">Online Customer Sales Report</h4>';

                                        },
                                        messageBottom: '<br/><h6 align="center">Developed By : MangoTech Solutions</h6>',
                                        exportOptions: {
                                            columns: [ 0,1, 2,3]
                                        }
                                    },
                            {
                                extend: 'excel',
                                messageTop: function () {
                                    return 'Customer Sales Report';
                                },
                                messageBottom: 'Developed By: MangoTech Solutions',
                                exportOptions: {
                                    columns: [ 0,1, 2,3]
                                }
                            }
                                ]
                            });
                           
                        }
                        

                }});
        }
        });

    </script>

}

POSOman/Views/OnlineCustomers/CustomerStatement.cshtml
@model IEnumerable<POSOman.Models.GetOnlineCustomerPaymentDateWise_Result>

@{
    ViewBag.Title = "Index";
}
<style>
    @@media print {
        html, body {
            height: 90vh;
        }
    }
</style>

<div class="content-body" id="content">
    <!-- DOM - jQuery events table -->
    <section id="dom">
        <div class="row">
            <div class="col-12">
                <h2>CUSTOMER STATEMENT</h2> <br />
                <div class="form-row">
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>From Date</label>
                        <input id="fromDate" type="date" class="form-control pickadate" placeholder="From Date" />

                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>To Date</label>
                        <input id="toDate" type="date" class="form-control pickadate" placeholder="To Date" />
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>Customer</label>
                        <input type="hidden" id="hdnAccountID" name="hdnAccountID">
                        <div class="input-group">
                            @Html.DropDownList("AccountID", new SelectList(ViewBag.customer, "Value", "Name"), "Select Customer", htmlAttributes: new { @class = "select2 form-control" })
                        </div>
                    </div>
                   
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label>Phone</label>
                        <br>
                        @Html.DropDownList("CustomerPhone", new SelectList(ViewBag.customerPhone, "Value", "Name"), "Select Phone", htmlAttributes: new { @class = "select2 form-control" })
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-1" hidden>
                        <label>Branch</label>
                        <div class="input-group">
                            @Html.DropDownList("Branch", new SelectList(ViewBag.Branch, "Value", "Name"), "Branch", htmlAttributes: new { @class = "select2 form-control" })
                        </div>
                    </div>
                    <div class="form-group mb-1 col-sm-12 col-md-2">
                        <label></label>
                        <br>
                        <button type="button" class="btn btn-primary" id="btnSearch">Search</button>
                    </div>
                </div>


                <div id="SearchResult">

                </div>
            </div>
        </div>

    </section>
</div>
@section scripts{

    <link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/sweetalert.css">
    <script src="~/Scripts/vendor/js/extensions/sweetalert.min.js" type="text/javascript"></script>

    <script>
        $("#AccountID").change(function () {
            var customerID = $('#AccountID').val();
            $('#hdnAccountID').val(customerID);
            $('#CustomerPhone').val(customerID).trigger('change.select2');
        });       
        $("#CustomerPhone").change(function () {
            var customerID = $('#CustomerPhone').val();
            $('#hdnAccountID').val(customerID);
            $('#AccountID').val(customerID).trigger('change.select2');           
        });
        $("#AccountID").select2();
        $("#CustomerPhone").select2();
        $("#btnSearch").on("click", function () {
            var accountID = $('#AccountID').val();
            var BranchID = $('#Branch').val();
            var fromDate = $('#fromDate').val();
            var toDate = $('#toDate').val();
            //var html = "<h3 style=margin-top:208px; margin-bottom:76px; align=center >Customer Statement</h3><br/>";
            var html = "";//"<h3 style=align=center>Customer Statement</h3><br/>";
            var Branch = $("#Branch option:selected").text();

            if (BranchID != "")
            { html += "<h4>Branch:  " + Branch + "</h4>"; }
            var vendorName = $("#AccountID option:selected").text();
            html += "<h4>Customer:  " + vendorName + "</h4>";
            if (fromDate != "" && toDate != "")
            { html += "<h4>From:    " + fromDate + "            TO:    " + toDate + " </h4>"; }
            if (accountID == 0)
            {
                swal("Select","Please Select Customer!","error");
            }
            else if (accountID > 0 )
            {
                $.ajax({
                    url: "@Url.Action("CustomerStatement", "OnlineCustomers")",
                    data: {
                    accountID : $('#AccountID').val(),
                    fromDate  : $('#fromDate').val(),
                    toDate: $('#toDate').val(),
                    BranchID : BranchID
                    },
                    success: function (data) {
                        if (data != null) {
                            $("#SearchResult").html(data);
                            var openingBalance = $("#openingBalance").val();
                            var closingBalance = $("#closingBalance").val();
                            html += "<h4>Opening Balance: " + openingBalance + "</h4>";
                            html += "<h4>Closing Balance: " + closingBalance + "</h4>";
                            //$.fn.dataTable.moment('D/M/YYYY', 'en-US');
                            $('#tblVendor').dataTable({
                                dom: 'Bfrtip',
                                ordering:false,
                                buttons: [
                                    {
                                        extend: 'print',
                                        messageTop: function () {
                                            //if ( printCounter === 1 ) {
                                            return '<img src="@ViewBag.Picture" class="brand-logo" align = "left" margin="10px"><h1 align="center">@ViewBag.CompanyName</h1><h5 align="center">@ViewBag.CompanyAddress</h5><h5 align="center">@ViewBag.CompanyLandline</h5><hr /><h4 align="center">Online Customer Statement</h4><h4>'+html+'</h4>';

                                        },
                                        title: '',
                                        messageBottom: '<br/><h6 align="center">Developed By : MangoTech Solutions</h6>',
                                        exportOptions: {
                                            columns: [ 1, 2, 3, 4, 5]
                                        }
                                    },
                            {
                                extend: 'excel',
                                messageTop: function () {
                                    return 'Customer Statement';
                                },
                                title: '',
                                messageBottom: 'Developed By: MangoTech Solutions',
                                exportOptions: {
                                    columns: [ 1, 2, 3, 4, 5]
                                }
                            }

                                ]
                            });

                        }


                }});
        }
        });

    </script>

}

POSOman/Views/OnlineCustomers/_CustomerSales.cshtml
﻿@model IEnumerable<POSOman.Models.GetOnlineCustomerSalesDateWise_Result>
<style>
    @@media print {
        @@page {
            /*size: A4; */
            margin-top: 40px;
            margin-bottom: 10px;
        }
</style>

<div class="card-content collapse show">
    <div class="row">
        <div class="card-body card-dashboard">
            @if (Model != null)
            {
                <table id="tblSO" class="table table-striped table-bordered alt-pagination" style="med">
                    <thead>
                        <tr>
                           
                            <th>
                                OrderNo
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Customer
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.TotalAmount)
                            </th>

                            <th></th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SOID)
                                </td>
                               
                                <td>
                                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.SalesDate))
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Customer)
                                </td>
                                
                                <td>
                                    @if (item.VAT > 0)
                                    { @(item.TotalAmount + item.VAT);
                                    }
                                    else if (item.VAT == 0 || item.VAT == null)
                                    { @Html.DisplayFor(modelItem => item.TotalAmount)}
                                </td>


                                <td>
                                    @Html.ActionLink("Receipt", "printOrder", "OnlineOrders", new { id = item.OrderID }, new { target = "_blank" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
               
            }
            else
            {
                <text>
                    <script type="text/javascript">
                        swal("No Data", "No Data Found!", "error");
                    </script>
                </text>
            }
        </div>
    </div>
</div>
@section scripts{
    <link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/sweetalert.css">
    <script src="~/Scripts/vendor/js/extensions/sweetalert.min.js" type="text/javascript"></script>
}

POSOman/Views/OnlineCustomers/_CustomerStatement.cshtml
@model IEnumerable<POSOman.Models.GetOnlineCustomerPaymentDateWise_Result>
<style>
    @@media print {
        @@page {
            /*size: A4; */
            margin-top: 60px;
            margin-bottom: 50px;
        }
    }
</style>
<div class="card-content collapse show">
    <div class="row">
        @if (Model != null)
            {
            <div class="col-md-4 mb-3">
                <label>Opening Balance</label>
                <input type="text" class="form-control" readonly="readonly" value=@Model.First().OpBalance id="openingBalance">
            </div>
            <div class="col-md-4 mb-3">

            </div>
                <div class="col-md-4 mb-3">

                    <label>Closing Balance</label>
                    @if (@Model.Last().Balance != "")
                    {<input type="text" class="form-control" readonly="readonly" value=@Model.Last().Balance id="closingBalance"> }
                    else
                    { <input type="text" class="form-control" readonly="readonly" value=0 id="closingBalance"> }

                </div>
                <div class="card-body card-dashboard">
                    <table id="tblVendor" class="table">
                        <thead>
                            <tr>
                                <th hidden>
                                    @Html.DisplayName("Branch")
                                </th>
                                <th>
                                    @Html.DisplayName("Date")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Detail)
                                </th>
                                @*<th>
                                        @Html.DisplayNameFor(model => model.Customer)
                                    </th>*@
                                <th>
                                    @Html.DisplayNameFor(model => model.Debit)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Credit)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Balance)
                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td hidden>
                                        @Html.DisplayFor(modelItem => item.BranchName)
                                    </td>
                                    <td>
                                        @*@Html.DisplayFor(modelItem => item.VoucherDate.ToString("dd/MM/yyyy"))*@
                                        @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.VoucherDate))
                                    </td>
                                    @if (item.Description != null)
                                    {
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Detail)
                                        </td> }

                                    @*<td>
                                            @Html.DisplayFor(modelItem => item.Customer)
                                        </td>*@
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Debit)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Credit)
                                    </td>
                                    <td>
                                        @if (item.Balance == "")
                                        { <label>0</label>}
                                        else
                                        {@Html.DisplayFor(modelItem => item.Balance);
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
        }
        else
        {
            <text>
                <script type="text/javascript">
                            swal("No Data", "No Data Found!", "error");
                </script>
            </text>
        }
    </div>
</div>
@section scripts{
    <link rel="stylesheet" type="text/css" href="~/Content/vendors/css/extensions/sweetalert.css">
    <script src="~/Scripts/vendor/js/extensions/sweetalert.min.js" type="text/javascript"></script>
}