POSOman/Models/DTO/BankAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POSOman.Models.DTO
{
    public class BankAccount
    {
        public int AccountTypeID { get; set; }
        public string AccountName { get; set; }
        public string AccountCode { get; set; }
        public string BankAccountNo { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsOperating { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string UserID { get; set; }

        public virtual tbl_AccountType tbl_AccountType { get; set; }
    }
}

POSOman/Controllers/BankAccountController.cs
using AutoMapper;
using POSOman.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Data.Entity;
using System.Web.Configuration;
using POSOman.Models.BLL;

namespace POSOman.Controllers
{
    public class BankAccountController : Controller
    {
        private dbPOS db = new dbPOS();
        UserActionsPerformed UserActions = new UserActionsPerformed();
       
        [Authorize]
        // GET: BankAccount
        [Authorize(Roles = "SuperAdmin,Admin,Accountant")]
        public ActionResult Index()
        {
            ViewBag.CompanyName = db.tbl_Company.Select(v => v.Name).FirstOrDefault();
            ViewBag.CompanyAddress = db.tbl_Company.Select(v => v.Address).FirstOrDefault();

            ViewBag.CompanyLandline = db.tbl_Company.Select(v => v.Landline).FirstOrDefault();
            ViewBag.CompanyCell = db.tbl_Company.Select(v => v.Cell).FirstOrDefault();
            ViewBag.CompanyEmail = db.tbl_Company.Select(v => v.Email).FirstOrDefault();
            ViewBag.Picture = db.tbl_Company.Select(v => v.Picture).FirstOrDefault();

            int branchId = 0;
            
            if (Session["BranchID"] != null)
            {
                branchId = Convert.ToInt32(Session["BranchID"]);
            }
            else
            {
                var user = User.Identity;
                string currentUserId = User.Identity.GetUserId();
                var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                branchId = currentUser.BranchID;
            }
            var bankAccounts = db.tbl_AccountDetails.Where(acd => acd.AccountTypeID == 27 && acd.BranchID == branchId).ToList();
            return View(bankAccounts);
        }
        [Authorize]
        // GET: Bank Account /Create
        [Authorize(Roles = "SuperAdmin,Admin,Accountant")]
        public ActionResult Create()
        {            
            return View();
        }
        // POST: bank Account/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.DTO.BankAccount account)
        {
            int branchId = 0;
            
            if (Session["BranchID"] != null)
            {
                branchId = Convert.ToInt32(Session["BranchID"]);
            }
            else
            {
                var user = User.Identity;
                string currentUserId = User.Identity.GetUserId();
                var currentUser = db.AspNetUsers.FirstOrDefault(x => x.Id == currentUserId);
                branchId = currentUser.BranchID;
            }
            account.BranchID = branchId;
            account.AccountTypeID = 27; // Client All Bank Accounts 
            account.Addby = 1;
            account.AddOn = DateTime.UtcNow.AddHours(5);
            account.IsDeleted = false;
            account.IsActive = true;
            account.UserID = HttpContext.User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                if (db.tbl_AccountDetails.Any(acd => acd.AccountName == account.AccountName && acd.Bank == account.Bank))
                {
                    ModelState.AddModelError("AccountName", "Bank Account Already Exists!");
                    return View("Create");
                }
               
                else
                {
                    Mapper.CreateMap<Models.DTO.BankAccount, tbl_AccountDetails>();                   
                    var accountModel = Mapper.Map<Models.DTO.BankAccount, tbl_AccountDetails>(account);
                    db.tbl_AccountDetails.Add(accountModel);
                    db.SaveChanges();
                    UserActions.MapActions(Convert.ToInt32(Session["LoginUserID"]), "Added Bank Accounts".ToString());

                    return RedirectToAction("Index");
                }
            }
           
            return View(account);
        }

        // GET: BankAccount/Edit/5
        [Authorize(Roles = "SuperAdmin,Admin,Accountant")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_AccountDetails tbl_AccountDetails = db.tbl_AccountDetails.Find(id);
            if (tbl_AccountDetails == null)
            {
                return HttpNotFound();
            }
            
            return View(tbl_AccountDetails);
        }

        // POST: Vendor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(tbl_AccountDetails accountModel)
        {
            accountModel.UpdateOn = DateTime.UtcNow.AddHours(5);
            if (ModelState.IsValid)
            {

                if (db.tbl_AccountDetails.Any(v => v.AccountName == accountModel.AccountName && v.AccountID!= accountModel.AccountID && v.Bank == accountModel.Bank))
                {
                    ModelState.AddModelError("AccountName", "Account Already Exists!");
                    return View("Edit");
                }                
                else
                {                    
                    db.Entry(accountModel).State = EntityState.Modified;
                    db.Entry(accountModel).Property(v => v.AccountTypeID).IsModified = false;
                    db.Entry(accountModel).Property(v => v.AddOn).IsModified = false;                    
                    db.Entry(accountModel).Property(v => v.Addby).IsModified = false;
                    db.Entry(accountModel).Property(v => v.UserID).IsModified = false;
                    db.Entry(accountModel).Property(v => v.BranchID).IsModified = false;
                    db.SaveChanges();
                    UserActions.MapActions(Convert.ToInt32(Session["LoginUserID"]), "Edited Bank Accounts".ToString());

                    return RedirectToAction("Index");
                }
            }
            
            return View(accountModel);
        }

        // GET: BankAccount/Delete/5
        [Authorize(Roles = "SuperAdmin,Admin,Accountant")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_AccountDetails tbl_AccountDetails = db.tbl_AccountDetails.Where(v => v.AccountID == id).FirstOrDefault();
            if (tbl_AccountDetails == null)
            {
                return HttpNotFound();
            }
            return View(tbl_AccountDetails);
        }

        // POST: BankAccount/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                bool isExist = db.tbl_JDetail.Any(p => p.AccountID == id);
                if (isExist)
                {
                    ModelState.AddModelError(string.Empty, "Record Cannot Be Deleted!");
                    tbl_AccountDetails tbl_AccountDetails = db.tbl_AccountDetails.Where(v => v.AccountID == id).FirstOrDefault();
                    if (tbl_AccountDetails == null)
                    {
                        return HttpNotFound();
                    }
                    return View(tbl_AccountDetails);
                }
                else
                {
                    tbl_AccountDetails tbl_AccountDetails = db.tbl_AccountDetails.Find(id);
                    db.tbl_AccountDetails.Remove(tbl_AccountDetails);
                    db.SaveChanges();
                    UserActions.MapActions(Convert.ToInt32(Session["LoginUserID"]), "Deleted Bank Accounts".ToString());

                    return RedirectToAction("Index");
                }
            }
            catch (Exception err)
            {
                ModelState.AddModelError(String.Empty, err.Message);
                return View("Index");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

POSOman/Views/BankAccount/Create.cshtml
@model POSOman.Models.DTO.BankAccount

@{
    ViewBag.Title = "Create";
}


<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <h3 class="content-header-title mb-0">Accounts</h3>
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="~/BankAccount">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Bank Account</a>
                    </li>
                    <li class="breadcrumb-item active">
                        <a href="#">Add</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <!-- Striped row layout section start -->
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-content collpase show">
                        <div class="card-body">
                            @using (Html.BeginForm("Create", "BankAccount",
    new { ReturnUrl = ViewBag.ReturnUrl },
    FormMethod.Post, new { @class = "form form-horizontal striped-rows form-bordered" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-body">
                                    <h4 class="form-section"><i class="ft-user"></i> Bank Account Info</h4>                          <div class="form-group row">
                                        @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                            @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.AccountCode, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.AccountCode, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.AccountCode, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.Bank, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.Bank, new { htmlAttributes = new { @class = "form-control" , required ="required" } })
                                            @Html.ValidationMessageFor(model => model.Bank, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.BankAccountNo, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.BankAccountNo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.BankAccountNo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>                                                                      
                                </div>
                                <div class="form-actions">
                                    @*<button type="button" class="btn btn-warning mr-1">
                                            <i class="ft-x"></i> Cancel
                                        </button>*@
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-check-square-o"></i> Save
                                    </button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Striped row layout section end -->
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

POSOman/Views/BankAccount/Delete.cshtml
@model POSOman.Models.tbl_AccountDetails

@{
    ViewBag.Title = "Delete";
}
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <h3 class="content-header-title mb-0">Bank Account</h3>
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/BankAccount">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Bank Account</a>
                    </li>
                    <li class="breadcrumb-item active">
                        <a href="#">Delete</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <!-- Striped row layout section start -->
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-content collpase show">
                        <div class="card-body">
                            <div class="form-body">
                                <h4 class="form-section"><i class="ft-user"></i>Are you sure you want to delete this?</h4>
                                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                <dl class="dl-horizontal">


                                    <dt>
                                        @Html.DisplayNameFor(model => model.AccountName)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.AccountName)
                                    </dd>

                                    <dt>
                                        @Html.DisplayNameFor(model => model.Bank)
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Bank)
                                    </dd>

                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </section>
    <!-- // Striped row layout section end -->
</div>

POSOman/Views/BankAccount/Edit.cshtml
@model POSOman.Models.tbl_AccountDetails

@{
    ViewBag.Title = "Edit";
}


<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2">
        <h3 class="content-header-title mb-0">Bank Accounts</h3>
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="~/BankAccount">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Bank Account</a>
                    </li>
                    <li class="breadcrumb-item active">
                        <a href="#">Edit</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <!-- Striped row layout section start -->
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-content collpase show">
                        <div class="card-body">
                            @using (Html.BeginForm("Edit", "BankAccount",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                     FormMethod.Post, new { @class = "form form-horizontal striped-rows form-bordered" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })                                
                                @Html.HiddenFor(model => model.AccountID)
                                <div class="form-body">
                                    <h4 class="form-section"><i class="ft-user"></i> Bank Account Info</h4>                          <div class="form-group row">
                                        @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                            @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.AccountCode, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.AccountCode, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.AccountCode, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.Bank, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.Bank, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                            @Html.ValidationMessageFor(model => model.Bank, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.BankAccountNo, htmlAttributes: new { @class = "col-md-3 label-control" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.BankAccountNo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.BankAccountNo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    @*<button type="button" class="btn btn-warning mr-1">
                                            <i class="ft-x"></i> Cancel
                                        </button>*@
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-check-square-o"></i> Save
                                    </button>
                                </div>

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Striped row layout section end -->
</div>

POSOman/Views/BankAccount/Index.cshtml
@model IEnumerable<POSOman.Models.tbl_AccountDetails>

@{
    ViewBag.Title = "Bank Accounts";
}<style>
    @@media print {
        html, body {
            height: 90vh;
        }
    }
</style>
<div class="content-body">
    <!-- DOM - jQuery events table -->
    <section id="dom">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">Bank Accounts</h2>  
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table-responsive">

                                <table id="tblBankAccount" class="table table-striped table-bordered alt-pagination">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.AccountName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.AccountCode)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Bank)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.BankAccountNo)
                                            </th>

                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AccountName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AccountCode)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Bank)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.BankAccountNo)
                                                </td>

                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.AccountID }) |
                                                    @Html.ActionLink("Delete", "Delete", new { id = item.AccountID })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section scripts{
    <script type="text/javascript">
        $('#tblBankAccount').DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'print',
                    messageTop: function () {

                        //if ( printCounter === 1 ) {
                        return '<img src="@ViewBag.Picture" class="brand-logo" align = "left" margin="10px"><h1  align="center">@ViewBag.CompanyName</h1><h5 align="center">@ViewBag.CompanyAddress </h5><h5 align="center">Contact: @ViewBag.CompanyCell</h5><hr /><h4 align="center">Bank Account List </h4>';

                    },
                    messageBottom: '<br/><h6 align="center">Developed By : MangoTech Solutions</h6>',

                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    }
                }
            ]
        });
    </script>
}